import {test} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {once} from 'node:events';
import {scryptSync,createHash} from 'node:crypto';
import {Store} from '../lib/store.mjs';
import {Accounts} from '../lib/accounts.mjs';
import vm from 'node:vm';
const log=n=>({date:'2026-09-01',kind:'training',pain:'舒适',note:'private-'+n,revision:0,entries:[{id:'pushup',step:1,sets:[n]}]});
test('多用户HTTP隔离、单次邀请、权限、密码重置与旧会话失效',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'fitness-multi-'));
 const child=spawn(process.execPath,['server.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,PORT:'0',HOST:'127.0.0.1',APP_ORIGIN:'',APP_INITIAL_PASSWORD:'',DATA_DIR:join(dir,'data'),BACKUP_DIR:join(dir,'backups')},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{child.kill();if(child.exitCode===null)await once(child,'exit');rmSync(dir,{recursive:true,force:true});});
 const base=await new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(new Error('startup')),10000);child.stdout.on('data',b=>{text+=b;const m=text.match(/http:\/\/localhost:\d+/);if(m){clearTimeout(timer);resolve(m[0]);}});child.on('error',reject);});
 const call=(who,path,method='GET',body,identity=who?.id)=>fetch(base+'/api/'+path,{method,headers:{...(who?{Cookie:who.cookie}:{}),...(identity?{'X-Fitness-User':identity}:{}),...(method!=='GET'?{'X-Fitness-Request':'1','Content-Type':'application/json'}:{})},body:body===undefined?undefined:JSON.stringify(body)});
 const auth=async(path,b)=>{const r=await call(null,path,'POST',b);assert.equal(r.status,200,await r.clone().text());return {id:(await r.json()).user.id,cookie:r.headers.get('set-cookie').split(';')[0]};};
 const owner=await auth('setup',{username:'owner',password:'012345'});
 assert.equal((await call(owner,'log','PUT',log(30))).status,200);
 const invite=await (await call(owner,'invites','POST',{})).json();
 const member=await auth('register',{username:'friend',password:'654321',code:invite.code});
 assert.equal((await call(null,'register','POST',{username:'third',password:'654321',code:invite.code})).status,400);
 assert.equal((await (await call(member,'state')).json()).logs.length,0);
 assert.equal((await call(member,'accounts')).status,403);
 assert.equal((await call(member,'invites','POST',{})).status,403);
 assert.equal((await call(member,'log','PUT',log(7),'owner')).status,409);
 assert.equal((await call(member,'log','PUT',log(7),null)).status,409);
 assert.equal((await call(member,'log','PUT',{...log(7),userId:'owner'})).status,200);
 assert.equal((await (await call(owner,'state')).json()).logs[0].entries[0].sets[0],30);
 assert.equal((await (await call(member,'state')).json()).logs[0].entries[0].sets[0],7);
 const csv=await (await call(member,'export?format=csv')).text();assert.ok(!csv.includes('private-30'));assert.ok(csv.includes('private-7'));
 const dashboard=await (await call(member,'dashboard?date=2026-09-01')).json();assert.deepEqual(dashboard.entries[0].sets,[7]);
 const settings=(await (await call(member,'state')).json()).settings;settings.plans[0].reps=9;
 assert.equal((await call(member,'settings','PUT',settings)).status,200);
 assert.notEqual((await (await call(owner,'state')).json()).settings.plans[0].reps,9);
 const backup=await (await call(owner,'export')).json();backup.logs=[{...log(12),date:'2026-09-02'}];
 assert.equal((await call(member,'import','POST',{data:backup})).status,200);
 assert.equal((await (await call(owner,'state')).json()).logs.length,1);
 assert.equal((await (await call(member,'state')).json()).logs.length,2);
 assert.equal((await call(member,'log','DELETE',{date:'2026-09-01',revision:1})).status,200);
 assert.equal((await (await call(owner,'state')).json()).logs.length,1);
 const oldCookie={...member};const changed=await call(member,'account/password','POST',{currentPassword:'654321',password:'111111'});assert.equal(changed.status,200);member.cookie=changed.headers.get('set-cookie').split(';')[0];
 assert.equal((await call(oldCookie,'state')).status,401);
 assert.equal((await call(null,'login','POST',{username:'friend',password:'654321'})).status,401);
 const reset=await (await call(owner,'invites','POST',{userId:member.id})).json();
 const resetUser=await auth('register',{code:reset.code,password:'222222'});assert.equal(resetUser.id,member.id);
 assert.equal((await call(member,'state')).status,401);
 assert.equal((await (await call(resetUser,'state')).json()).logs.length,1);
 assert.equal((await call(owner,'state')).status,200);
});
test('旧版数据、密码、会话原样归属管理员；成员备份独立；邀请过期和限流',async()=>{
 const dir=mkdtempSync(join(tmpdir(),'fitness-migration-')),owner=new Store(join(dir,'data'),join(dir,'backups'));
 const salt='migration-test',p={salt,key:scryptSync('012345',salt,64).toString('hex')};owner.set('password',p);owner.saveLog(log(30),0);
 const token='legacy-session';owner.db.prepare('INSERT INTO sessions VALUES(?,?)').run(createHash('sha256').update(token).digest('hex'),Date.now()+60000);
 const accounts=new Accounts(owner,join(dir,'data'),join(dir,'backups'));
 try{await accounts.init();assert.equal(accounts.current(token).id,'owner');assert.equal(accounts.login({password:'012345'},'local').id,'owner');assert.equal(owner.logs().length,1);
  await accounts.init();assert.equal(accounts.list().length,1);
  const invite=accounts.invite();accounts.db.prepare('UPDATE invitations SET expires=0').run();assert.throws(()=>accounts.redeem({code:invite.code,username:'friend',password:'111111'},'local'));
  const friend=accounts.redeem({code:accounts.invite().code,username:'friend',password:'111111'},'local');const other=accounts.store(friend);other.saveLog(log(7),0);const file=await other.snapshot();
  const {DatabaseSync}=await import('node:sqlite');const saved=new DatabaseSync(join(dir,'backups','users',friend.id,file),{readOnly:true});assert.equal(JSON.parse(saved.prepare('SELECT body FROM logs').get().body).entries[0].sets[0],7);assert.equal(saved.prepare("SELECT name FROM sqlite_master WHERE name='users'").get(),undefined);saved.close();
  for(let i=0;i<10;i++)assert.throws(()=>accounts.login({username:'friend',password:'000000'},'bad'+i),e=>e.status===401);
  assert.throws(()=>accounts.login({username:'friend',password:'111111'},'different'),e=>e.status===429);
 }finally{await accounts.close();rmSync(dir,{recursive:true,force:true});}
});
test('浏览器草稿按账号隔离，旧草稿只迁移给管理员',()=>{
 const values=new Map([['fitness-draft-2026-09-01',JSON.stringify({note:'legacy'})]]);const localStorage={getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
 // Object.keys(localStorage) reflects actual storage keys in a browser.
 Object.defineProperty(localStorage,'fitness-draft-2026-09-01',{enumerable:true,value:'legacy'});
 const context=vm.createContext({Intl,Date,console,localStorage});const source=readFileSync(new URL('../public/app.js',import.meta.url),'utf8').split("window.addEventListener('beforeinstallprompt'")[0];
 vm.runInContext(source+'\nglobalThis.test={activate:activateUser,storage};',context);
 context.test.activate({id:'friend',username:'friend'});assert.equal(context.test.storage.get('draft-2026-09-01'),null);context.test.storage.set('draft-2026-09-01',{note:'friend'});
 context.test.activate({id:'owner',username:'owner'});assert.equal(context.test.storage.get('draft-2026-09-01').note,'legacy');context.test.activate({id:'friend',username:'friend'});assert.equal(context.test.storage.get('draft-2026-09-01').note,'friend');
});